apply plugin: 'com.android.application'

android {
    namespace 'com.greco.golftracker'
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.greco.golftracker"
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
